### ISSUE TITLE
Couldn't install pIMZ following the instructions

### ISSUE THREAD

**Issue by ranabanik** [mjoppich/pIMZ#2]
<pre>(ims36) <font color="#8AE234"><b>banikr2@banikr</b></font>:<font color="#729FCF"><b>~</b></font>$ sudo pip3 install pIMZ
<font color="#C4A000">The directory &apos;/home/banikr2/.cache/pip/http&apos; or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&apos;s -H flag.</font>
<font color="#C4A000">The directory &apos;/home/banikr2/.cache/pip&apos; or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&apos;s -H flag.</font>
Collecting pIMZ
<font color="#CC0000">  Could not find a version that satisfies the requirement pIMZ (from versions: )</font>
<font color="#CC0000">No matching distribution found for pIMZ</font>
</pre>

What could be done to check?

**Comment by mjoppich** [comment]
Hi,

sorry for the late answer (holidays ...).

What version of python3 do you have? My guess is, that the limiting version compatibility on pip is the factor here.

I would recommend to simply `git clone https://github.com/mjoppich/pIMZ.git` and then run the setup from the `pIMZ` folder: `python3 setup.py install --user` or with sudo, depending on where you want to install things to.
This also has the benefit of having the most up-to-date version ;)

**Comment by ranabanik** [comment]
Do you have a suggestion from which directory in the terminal I shall run the `git clone`? I used the following in the terminal: 

`banikr2@banikr:~$ git clone https://github.com/mjoppich/pIMZ.git` <br>
`banikr2@banikr:~/pIMZ (master)$ python3 setup.py install --user`
This generate the following error: 

`ModuleNotFoundError: Please install Cython with a version >= 0.28.5 in order to build a scikit-learn from source.`
`banikr2@banikr:~/pIMZ (master)$ `

Any idea how to debug this? I have existing python environments where scikit-learn is installed.

**Comment by mjoppich** [comment]
You'd need to run the install with the `python3` environment where you already got scikit-learn installed.

As we setup circleCI for pIMZ (https://github.com/mjoppich/pIMZ/blob/master/.circleci/config.yml) you can check what dependencies are needed (if you're on some kind of Ubuntu) :)

**Comment by ranabanik** [comment]
- git cloned

`(ims36) banikr2@banikr:~/PycharmProjects$ git clone https://github.com/mjoppich/pIMZ.git`

- setup

`ImportError: Cython not found! Please install cython and try again`
Installing cython:
`(ims36) banikr2@banikr:~/PycharmProjects/pIMZ (master)$ pip install Cython`
`RuntimeError: Cannot install on Python version 3.6.13; only versions >=3.7,<3.10 are supported.`

I guess it doesn't work with python=3.6 version... :(
Trying to install with 3.7

**Comment by ranabanik** [comment]
Finally got to install with the following changes: 

```error: numpy 1.21.2 is installed but numpy<1.21,>=1.17 is required by {'numba'}
(ims37) banikr2@banikr:~/PycharmProjects/pIMZ (master)$ 
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2
Successfully installed numpy-1.20.3

**Comment by mjoppich** [comment]
Just out of curiosity, what was the problem with numpy 1.21 ?

Just asking, because the latest CI build completed successfully with `numpy-1.21.2` :)

**Comment by ranabanik** [comment]
Yeah, the installation worked fine after:
`pip install numpy==1.20.3`
